######################## default configuration ####################
baseURL = "https://www.betterify.in/"
title = "Betterify - Better Financial Management"
theme = "andromeda-light"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# google analytics
googleAnalytics = "G-3ZTYKP665K" # example: UA-123-45, for more info, read the article https://support.google.com/analytics/answer/1008080?hl=en
# disqus short name
disqusShortname = "betterify" # get your shortname form here : https://disqus.com

############################# Modules ##############################
[module]
[module.hugoVersion]
extended = true
min = "0.83.1"

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "WebAppManifest"]

[imaging]
quality = 100

[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "-1h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

[markup]
[markup.goldmark.renderer]
unsafe= true

[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]

[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"

[markup.tableOfContents]
    startLevel = 1
    endLevel = 5
    ordered = true

[social]
  twitter = "BetterifyIn"

[params]
  mainSections = ["posts"]
  description = "We help in Better Management of Finances, Accounts, Investments, and Taxes (FAIT). Let’s Betterify!!"
  twitter_cards = true 
  images = ["https://docs.google.com/drawings/d/e/2PACX-1vTrr7ZmAg6FBsQEflTT4DMDDCmQCZoGPxd1TACZj8qEhwL1jZ-t_pVN8-gsalVLdOBNJs3yI0NAeGHN/pub?w=960&amp;h=600"] # Hugo’s Twitter Card template requirement
  title = "Betterify - Better Financial Management"
  # tag = "tags"
  # https://res.cloudinary.com/dnbgvuilt/image/upload/v1672305395/Twitter_Card_Betterify_1_tze6dr.png

[taxonomies]
  category = "categories" # Tags and categories don’t work if not added
  series = "series" # Hugo’s Open Graph template requirement 
  tag = "tags" # Tags and categories don’t work if not added
  # year = "year"
	# month = "month"
  # mainSections= "blog"

# [twitter_summary]
#   card = "summary"
#   site = "@BetterifyIn"
#   title = "We help you Betterify!!"
#   description = "We help in Better Management of Finances, Accounts, Investments, and Taxes (FAIT). Let’s Betterify!!"
#   images = ["https://littlekendra.com/images/manuel-CANL3bzp6wU-unsplash.jpg"]

# [twitter_large]
#   card = "summary_large_image"
#   site = "@BetterifyIn"
#   creator = "@AvadhootMe"
#   title = "We help you Betterify!!"
#   description = "We help in Better Management of Finances, Accounts, Investments, and Taxes (FAIT). Let’s Betterify!!"
#   images = ["https://littlekendra.com/images/manuel-CANL3bzp6wU-unsplash.jpg"]

# [taxonomies]
# 	tag = "tags"
# 	category = "categories"
# 	year = "year"
# 	month = "month"

# [permalinks]
#     post = "/post/:year/:month/:slug/"
#     year = "/post/:slug/"
#     month = "/post/:slug/"

# [permalinks]
#     blog = "/blog/:year/:month/:slug/"
#     year = "/blog/:slug/"
#     month = "/blog/:slug/"

# [permalinks]
#     # Optional. Change the permalink format for the 'post' content type.
#     # The format shown here is the same one Jekyll/Octopress uses by default.
#     post = "/:section/:slug"
#     mainSections= "blog"

# [caches]
#   [caches.getcsv] # A value of -1 will cache the file forever, 0 turns the cache off, or you can specify a time.
#     maxAge = 0
#   [caches.getjson] # Setting the maxAge to 14h, for example, means that if more than 14 hours have elapsed since your last build, your remote data file will be updated on your next build.
#     maxAge = "14h"

[caches.getcsv] # A value of -1 will cache the file forever, 0 turns the cache off, or you can specify a time.
    maxAge = 0

[minify]
  minifyOutput = true # Using PurgeCSS is a great way of reducing the compiled CSS size, but consider always minifying the other static assets at build time by adding this to your Hugo config file. 
# This will minify your CSS, HTML, JS, JSON, SVGs and XML automatically.

[build]
  writeStats = true # Installing PurgeCSS. This tells Hugo to write a hugo_stats.json file to the project root as part of the build. It includes all tags, classes, and ids from your *.html templates.




