######################## default configuration ####################
baseURL = "https://www.betterify.in/"
title = "Betterify - Better Financial Management"
theme = "andromeda-light"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# google analytics
googleAnalytics = "G-3ZTYKP665K" # example: UA-123-45, for more info, read the article https://support.google.com/analytics/answer/1008080?hl=en
# disqus short name
disqusShortname = "betterify" # get your shortname form here : https://disqus.com

############################# Modules ##############################
[module]
[module.hugoVersion]
extended = true
min = "0.83.1"

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "WebAppManifest"]

[imaging]
quality = 100

[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

[markup]
[markup.goldmark.renderer]
unsafe= true

[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]

[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"

[markup.tableOfContents]
    startLevel = 1
    endLevel = 5
    ordered = false

[social]
  twitter = "BetterifyIn"

[params]
  mainSections = ["posts"]
  description = "We help in Better Management of Finances, Accounts, Investments, and Taxes (FAIT). Let’s Betterify!!"
  twitter_cards = true 
  images = ["https://res.cloudinary.com/dnbgvuilt/image/upload/v1670586727/Twitter_Card_Betterify_lemidm.png"] # Hugo’s Twitter Card template requirement
  title = "Betterify - Better Financial Management"
  # tag = "tags"

[taxonomies]
  series = 'series' # Hugo’s Open Graph template requirement 
  tag = "tags" # Tags and categories don’t work if not added
  # category = "categories"
  # year = "year"
	# month = "month"
  # mainSections= "blog"

# [twitter_summary]
#   card = "summary"
#   site = "@BetterifyIn"
#   title = "We help you Betterify!!"
#   description = "We help in Better Management of Finances, Accounts, Investments, and Taxes (FAIT). Let’s Betterify!!"
#   images = ["https://littlekendra.com/images/manuel-CANL3bzp6wU-unsplash.jpg"]

# [twitter_large]
#   card = "summary_large_image"
#   site = "@BetterifyIn"
#   creator = "@AvadhootMe"
#   title = "We help you Betterify!!"
#   description = "We help in Better Management of Finances, Accounts, Investments, and Taxes (FAIT). Let’s Betterify!!"
#   images = ["https://littlekendra.com/images/manuel-CANL3bzp6wU-unsplash.jpg"]

# [taxonomies]
# 	tag = "tags"
# 	category = "categories"
# 	year = "year"
# 	month = "month"

# [permalinks]
#     post = "/post/:year/:month/:slug/"
#     year = "/post/:slug/"
#     month = "/post/:slug/"

# [permalinks]
#     post = "/:year/:month/:slug/"
#     year = "/:slug/"
#     month = "/:slug/"

# [permalinks]
#     # Optional. Change the permalink format for the 'post' content type.
#     # The format shown here is the same one Jekyll/Octopress uses by default.
#     post = "/:section/:slug"
#     mainSections= "blog"
	