# main menu
[[main]]
name = "About"
url = "about/"
weight = 1

[[main]]
name = "Apps"
weight = 4
hasChildren = true

  [[main]]
  parent = "Apps"
  name = "BSE AllCap"
  url = "bse-allcap/"
  weight = 2

  [[main]]
  parent = "Apps"
  name = "Nifty"
  url = "nifty/"
  weight = 1

  [[main]]
  parent = "Apps"
  name = "Targets"
  url = "bse-nse-stock-targets/"
  weight = 3

  [[main]]
  parent = "Apps"
  name = "Adani Group"
  url = "adani-group/"
  weight = 4

[[main]]
name = "Blog"
url = "blog/"
weight = 3

[[main]]
weight = 4
name = "Pages"
hasChildren = true

  [[main]]
  parent = "Pages"
  name = "Blog Details"
  url = "blog/betterify/"
  weight = 1

  [[main]]
  parent = "Pages"
  name = "Privacy"
  url = "privacy/"
  weight = 7

  [[main]]
  parent = "Pages"
  name = "RSS Feed"
  url = "rss-feed/"
  weight = 8

  [[main]]
  parent = "Pages"
  name = "Tags"
  url = "tags/"
  weight = 9

  [[main]]
  parent = "Pages"
  name = "Categories"
  url = "categories/"
  weight = 10
  
[[main]]
name = "Contact"
url = "contact/"
weight = 5

[[main]]
name = "Search"
url = "search/"
weight = 6

# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Blog"
url = "blog/"
weight = 2

[[footer]]
name = "Blog Details"
url = "blog/betterify/"
weight = 3

[[footer]]
name = "Privacy"
url = "privacy/"
weight = 4