# main menu
[[main]]
name = "About"
url = "about/"
weight = 1

[[main]]
name = "Apps"
url = "apps/"
weight = 5

[[main]]
name = "Blog"
url = "blog/"
weight = 3

[[main]]
weight = 4
name = "Pages"
hasChildren = true

  [[main]]
  parent = "Pages"
  name = "Blog Details"
  url = "blog/post-1/"
  weight = 1

  [[main]]
  parent = "Pages"
  name = "Privacy"
  url = "privacy/"
  weight = 7
  
[[main]]
name = "Contact"
url = "contact/"
weight = 5


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Blog"
url = "blog/"
weight = 2

[[footer]]
name = "Blog Details"
url = "blog/post-1/"
weight = 3

[[footer]]
name = "Privacy"
url = "privacy/"
weight = 4