[build]
  publish = "public"
  command = "hugo --minify --gc"
  #command = "tinacms build && hugo --minify --gc"  // Caused build error.
  
[build.environment]
  HUGO_VERSION = "0.142.0" # use a stable Netlify-supported version as per ChatGPT 0.115.4
  HUGO_BASEURL = "https://www.betterify.in/"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"  

[[headers]]
  for = "/*" # This defines which paths this specific [[headers]] block will cover.

[headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  Referrer-Policy = "same-origin"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[redirects]]
from = "https://betterify.netlify.app/"
to = "https://www.betterify.in/"
status = 301
force = true